name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Create .env file
      run: echo "${{ secrets.ENV }}" > .env

    - name: Decode and create firebaseService.json
      run: echo "${{ secrets.FIREBASE64 }}" | base64 --decode > src/firebaseService.json

    - name: Install dependencies
      run: npm install

    - name: Run start script
      run: npm run start

    # Add any additional steps here if needed, such as deploying to a server
